version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - node generate_aws_exports.js
      - cd frontend/app
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  type: s3
  files:
    - '**/*'
  base-directory: frontend/app/build