version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install -g npm@latest
      - echo Checking for REACT_APP_API_KEY: $REACT_APP_API_KEY
      - echo Checking for REACT_APP_GRAPHQL_ENDPOINT: $REACT_APP_GRAPHQL_ENDPOINT
      - echo Checking for REACT_APP_REGION: $REACT_APP_REGION
      - node generate_aws_exports.js
      - cd frontend/app
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  type: s3
  files:
    - '**/*'
  base-directory: frontend/app/build