// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://lfoafcz6dngg5gthcvus5lltra.appsync-api.ap-northeast-1.amazonaws.com/graphql',
          region: 'ap-northeast-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-tp43ysno3jhi5gsysworvrwswm'
        }
    }
};

export default config;