# Generated by Django 5.0.1 on 2024-01-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_id",
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
