# Generated by Django 5.0.1 on 2024-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_company_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_own_company",
            field=models.BooleanField(default=False),
        ),
    ]
